name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run AI review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_MODEL: claude-3-5-sonnet-latest
          MAX_TOTAL_BYTES: "250000"
          POST_INLINE_COMMENTS: "false"
        run: |
          python - <<'PY'
          import os, json, asyncio
          from src.review import run_review
          repo = os.environ.get("GITHUB_REPOSITORY")
          with open(os.environ["GITHUB_EVENT_PATH"], "r") as f:
              event = json.load(f)
          owner, name = repo.split("/")
          pr_number = event["number"]
          asyncio.run(run_review(owner, name, pr_number))
          PY
